default: &default
  adapter: async
  channel_prefix: <%= "#{Rails.env}_action_cable"  %>

development:
  <<: *default

test:
  adapter: test
  channel_prefix: <%= "#{Rails.env}_action_cable"  %>

staging:
  <<: *default

production:
  <<: *default
